### ISSUE TITLE
画像がレスポンシブでない

### ISSUE THREAD

**Issue by fukuchiharuki** [fukuchiharuki/LuLu-a-skin-for-PukiWiki#8]
ウィンドウの幅が狭いと画像が普通にカードからはみ出す。

**Comment by fukuchiharuki** [comment]
こうかな。
```css
.img_margin {
	margin: 0 0 16px;
}

.img_margin > a > img {
	max-width: 100%;
	height: auto !important;
}
```
