### ISSUE TITLE
引用の前後が美しくない

### ISSUE THREAD

**Issue by fukuchiharuki** [fukuchiharuki/LuLu-a-skin-for-PukiWiki#9]
開始を目立つように書いて
閉じは書かない方がいいかも。

**Comment by fukuchiharuki** [comment]
こうかな。
```css
blockquote {
	margin-right: 0;
}

blockquote:before {
	color: gray;
	font-size: 80px;
	left: -48px;
	top: -32px;	
}

blockquote:after {
	display: none;
}
```
